# fly.toml app configuration file generated for non-sei-solo-corsi-corsi on 2025-08-18T19:39:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'non-sei-solo-corsi-corsi'
primary_region = 'fra'
console_command = '/rails/bin/rails console'

[build]
  builder = 'paketobuildpacks/builder:base'

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'

[processes]
  app = './bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
